plugins {
    id 'com.android.library' version '8.2.2'
    id 'maven-publish'
}

android {
    namespace 'com.github.matheuscruzsouza.nanospring'
    compileSdk 36

    defaultConfig {
        minSdk 25
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    api 'com.samskivert:jmustache:1.15'
    api 'org.nanohttpd:nanohttpd:2.3.1'
    api 'org.nanohttpd:nanohttpd-nanolets:2.3.1'
    api 'com.google.code.gson:gson:2.8.9'
    testImplementation 'junit:junit:4.13.2'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.matheuscruzsouza'
                artifactId = 'nano-spring'
                version = System.getenv('VERSION') ?: (System.getenv('GITHUB_REF_NAME')?.replaceFirst('^v', '')?.matches('^[0-9].*') ? System.getenv('GITHUB_REF_NAME').replaceFirst('^v', '') : '1.6.0')
            }
        }
        repositories {
            maven {
                name = 'GitHubPackages'
                url = uri("https://maven.pkg.github.com/${System.getenv('GITHUB_REPOSITORY') ?: 'matheuscruzsouza/AndroidServer'}")
                credentials {
                    username = System.getenv('GITHUB_ACTOR') ?: System.getenv('USERNAME')
                    password = System.getenv('GITHUB_TOKEN') ?: System.getenv('TOKEN')
                }
            }
        }
    }
}
