plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'com.github.matheuscruzsouza.nanospring'
    compileSdk 36

    defaultConfig {
        minSdk 25
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    api 'com.samskivert:jmustache:1.15'
    api 'org.nanohttpd:nanohttpd:2.3.1'
    api 'org.nanohttpd:nanohttpd-nanolets:2.3.1'
    api 'com.google.code.gson:gson:2.8.9'
}
