[versions]
agp = "8.2.2"
nanohttpd = "2.3.1"
gson = "2.8.9"
jmustache = "1.15"
junit = "4.13.2"
mockito = "5.10.0"

[libraries]
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
nanohttpd-nanolets = { module = "org.nanohttpd:nanohttpd-nanolets", version.ref = "nanohttpd" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jmustache = { module = "com.samskivert:jmustache", version.ref = "jmustache" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
